### ISSUE TITLE
tl866a fusebits risc of locking oneself out. Should be in the docs.

### ISSUE THREAD

**Issue by bwack** [djtulan/nunchuk64#5]
I'm making a handful of the boards and programming them with the TL866A.
Half of the boards programmed fine, but the rest did not.
After research it was the fusebits in minipro that got changed. Also I got them back to life by supplying a clock signal in on the button/XTAL and reprogramming them.

I thought the .hex file carried the fusebits, but no. These have to be set manually, and I found them in the makefile.  Could you please put the fusebits information in the programming documentation and together with the instructions for using tl866a?

**Comment by djtulan** [comment]
bwack is absolutely right. Take care of the fusebits. Best is not to play around with it. Leave the default fusebits for ATmega328p.

**Comment by bwack** [comment]
Maybe it is not the correct place to ask, but did you write the I2C communication yourself ? I'm looking into adding I2C on an ATTINY for my c64 saver addon board project.
