### ISSUE TITLE
LED is flashing only, no function

### ISSUE THREAD

**Issue by VintageProject** [djtulan/nunchuk64#6]
When trying the Nunchuk64 with Nintendo Nunchuks, I found that the LED is flashing constantly with approx. 1 Hz, much like the basic Blinky program. The flashing happens no matter if a C64 is hooked up or a Nunchuk.
If I power the board from a bench PSU with 5V via the DB9 or the programming header, it also flashes.

Although I read that the LED on pin 2 of the ATMega328P is hooked up for debugging, I couldn't find any documentation on how to read its signal.

What does this constant flashing mean?

I tried reprogramming the MCU with this v1.2.0 release, but it didn't change.
https://github.com/djtulan/nunchuk64/releases

**Comment by djtulan** [comment]
The Flashing comes from the Watchdog Timer, which is set to 1sec.
The WDT resets the device if the I2C communication times out -> no anwer.
If no controller is connected and the device flashes with 1Hz, then you have a soldering bug.
Some newer Nunchuks don't work with the Adapter, this could be the issue.

**Comment by bwack** [comment]
@VintageProject Are your Nunchucks the black ones with higher I2C frequencies ? Maybe realted issue #2.

**Comment by VintageProject** [comment]
@bwack Yes, they're black oney, but I didn't get around measuring anything or diving into the code.
I did test with another controller, and the faulty board didn't seem to work with that, either.

**Comment by bwack** [comment]
Faulty board.. I sent two working boards!

**Comment by VintageProject** [comment]
You did. I think the microcontroller got knackered somehow.
I have replacements somewhere and I'm going to try and swap it.

As for the function with the Nunchuks, we can close this one here.
