### ISSUE TITLE
Ready made HEX

### ISSUE THREAD

**Issue by mamejay** [djtulan/nunchuk64#7]
Hello there.  I am good at soldering but terrible on the software side and not sure about compiling the source code.  I am a windows user and have no idea where to start.
Is it possible to get a ready made HEX file for the Atmega chip?
Also on a previous issue you mention to just leave all fuse values alone.  so if using AVRdude I would just use a standard command and leave all fuse values out of the command?
Thanks

**Comment by djtulan** [comment]
You don't have to compile it by yourself you can just use the latest release:
https://github.com/djtulan/nunchuk64/releases
There is also the HEX file.

The call for avrdude should look like this, depending on your programmer
I don't know if it is the same for Windows
**avrdude -p atmega328p -c usbtiny -F -v  -v  -U flash:w:nunchuk64.hex**

**Comment by mamejay** [comment]
Thank you very much for that.  I feel a bit silly now.
