### ISSUE TITLE
Huge lag on Left and down movements

### ISSUE THREAD

**Issue by mamejay** [djtulan/nunchuk64#8]
Hi there djtulan.
I managed to make a couple of adapters last night.
They are recognising but I am getting huge lag on left and down movement.  Also slight lag on all other movements but left and down is the worst.
I purchased the following SNES mini controllers.
https://www.ebay.com.au/itm/Wireless-Controller-Gamepad-For-Super-Nintendo-SNES-Classic-Mini-Edition-Console/222907612359?ssPageName=STRK%3AMEBIDX%3AIT&var=521731659465&_trksid=p2057872.m2749.l2649

Any ideas on what could be the issue?  I have use 22uf ceramic caps.  Could this be the issue?
Everything else is exactly as you had in your BOM.  Thanks

**Comment by djtulan** [comment]
Hi!

I also got some of these. The quality is not so nice. Do you have always the same lag or is it changing? Maybe it is a contact problem inside the controller? One of mine had troubles with one direction as i remember right. I opened the controller and moved the membrane to the correct position, than it was slightly better.

The 22uF ceramic caps should not cause that troubles.

**Comment by mamejay** [comment]
I will test over this week with a Nintendo nunchuk controller I have and see if I get the same problems.  I will also test these controllers on my SNES mini and see if I get similar results.
Yes I get the same lag from both controllers all the time

**Comment by mamejay** [comment]
Hi djtulan,
You are correct.  The pads are shit.  I managed to get them workable by adding solder to the contacts on the game pad to make the dpad presses shorter.  This has made them much better to use and lag is pretty much gone now.
Attached are pictures in case others need to do the same.

![20181219_220924_resized](https://user-images.githubusercontent.com/24428736/50219475-706a8780-03e3-11e9-8e68-48aaa96b7153.jpg)
![20181219_221021_resized](https://user-images.githubusercontent.com/24428736/50219479-719bb480-03e3-11e9-880d-8e193cde9906.jpg)

**Comment by djtulan** [comment]
Nice hack :+1:   Thank you for the pictures.
I will close the issue now.
